version: "2"
services:
  botapadd:
    ports:
      - "5000:5000"
    environment:
      - APP_DEBUG=true
      - PRODUCTION=false
      - BIND_PORT=5000
    restart: "no"
    volumes:
      - ./secret:/var/padagraph-botapadd/

# TODO/consider: possibility of using nodemon in dev only, for automatic reloading within container when we change a source file